# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24f4f944161113caa93f82dc0b95ea85069e5b98c0c6377ebfe0c641b2e600d77d7e331338d4b8cfa8e26e5056b97ee640a67b6577085335c840ca72de932973

test:
  secret_key_base: 0893e556183fd404129f1e9fea4c9cb9d8b58e992f87e9c7f93e2c967b7941a441366fc34b97c0f55e5a496cbdee822830c021a4d8acc4ec9d7a3d6025ded56d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
